version: '2'
services:
  vacaciones:
    image: ghcr.io/zamoks95/tiendaonline-frontend/vacaciones
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - STRAPI_PAGE=vacaciones
        - GTAG=G-3LX28H0PH8
    restart: always