version: '2'
services:
  vacaciones:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - STRAPI_PAGE=vacaciones
        - GTAG=G-3LX28H0PH8
    restart: always

  juegosdemesa:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - STRAPI_PAGE=juegosdemesa
        - GTAG=G-3LX28H0PH8
    restart: always